source 'https://rubygems.org'

gem 'rails', '4.0.3'

group :development do
  gem 'sqlite3', '1.3.8'
end

gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '3.1.0'
gem 'jbuilder', '~> 1.2'
gem 'haml-rails'

group :development, :test do
  gem 'rspec-rails'
end

group :production do
  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end

gem 'sass-rails', '4.0.1'
gem 'bootstrap-sass', '3.1.1.0'
gem 'rmagick', '~> 2.13.2'
gem 'carrierwave', '~> 0.10.0'

gem 'jcrop-rails-v2', '~> 0.9.12.3'
gem 'simple_form', '~> 3.0.1'
gem 'quiet_assets', '~> 1.0.2'

gem 'will_paginate', '~> 3.0.5'
gem 'betterlorem', '~> 0.1.2'
gem 'bootstrap-will_paginate', '~> 0.0.10'

gem 'carrierwave-ftp', :require => 'carrierwave/storage/ftp/all' # both FTP/SFTP
